cp src-mac/com/prophetvs/editor/AiffFile.java src/com/prophetvs/editor/AiffFile.java
cp src-mac/com/prophetvs/editor/AmpEnvelopeControl.java src/com/prophetvs/editor/AmpEnvelopeControl.java
cp src-mac/com/prophetvs/editor/Bank.java src/com/prophetvs/editor/Bank.java
cp src-mac/com/prophetvs/editor/BankWindow.java src/com/prophetvs/editor/BankWindow.java
cp src-mac/com/prophetvs/editor/ControlMapper.java src/com/prophetvs/editor/ControlMapper.java
cp src-mac/com/prophetvs/editor/CustomControl.java src/com/prophetvs/editor/CustomControl.java
cp src-mac/com/prophetvs/editor/EnvelopeControl.java src/com/prophetvs/editor/EnvelopeControl.java
cp src-mac/com/prophetvs/editor/FilterEnvelopeControl.java src/com/prophetvs/editor/FilterEnvelopeControl.java
cp src-mac/com/prophetvs/editor/KeyboardView.java src/com/prophetvs/editor/KeyboardView.java
cp src-mac/com/prophetvs/editor/KeyboardWindow.java src/com/prophetvs/editor/KeyboardWindow.java
cp src-mac/com/prophetvs/editor/MixEnvelopeControl.java src/com/prophetvs/editor/MixEnvelopeControl.java
cp src-mac/com/prophetvs/editor/Patch.java src/com/prophetvs/editor/Patch.java
cp src-mac/com/prophetvs/editor/PatchCellRenderer.java src/com/prophetvs/editor/PatchCellRenderer.java
cp src-mac/com/prophetvs/editor/PatchNumberTransform.java src/com/prophetvs/editor/PatchNumberTransform.java
cp src-mac/com/prophetvs/editor/RandomTransform.java src/com/prophetvs/editor/RandomTransform.java
cp src-mac/com/prophetvs/editor/RawFile.java src/com/prophetvs/editor/RawFile.java
cp src-mac/com/prophetvs/editor/ROMPatchNumberTransform.java src/com/prophetvs/editor/ROMPatchNumberTransform.java
cp src-mac/com/prophetvs/editor/SetTransform.java src/com/prophetvs/editor/SetTransform.java
cp src-mac/com/prophetvs/editor/TransferablePatch.java src/com/prophetvs/editor/TransferablePatch.java
cp src-mac/com/prophetvs/editor/TransferableWave.java src/com/prophetvs/editor/TransferableWave.java
cp src-mac/com/prophetvs/editor/Transform.java src/com/prophetvs/editor/Transform.java
cp src-mac/com/prophetvs/editor/TransformOperation.java src/com/prophetvs/editor/TransformOperation.java
cp src-mac/com/prophetvs/editor/VariationGenerator.java src/com/prophetvs/editor/VariationGenerator.java
cp src-mac/com/prophetvs/editor/VaryCellEditor.java src/com/prophetvs/editor/VaryCellEditor.java
cp src-mac/com/prophetvs/editor/VaryCellRenderer.java src/com/prophetvs/editor/VaryCellRenderer.java
cp src-mac/com/prophetvs/editor/VaryPanel.java src/com/prophetvs/editor/VaryPanel.java
cp src-mac/com/prophetvs/editor/VaryWindow.java src/com/prophetvs/editor/VaryWindow.java
cp src-mac/com/prophetvs/editor/VSException.java src/com/prophetvs/editor/VSException.java
cp src-mac/com/prophetvs/editor/Wave.java src/com/prophetvs/editor/Wave.java
cp src-mac/com/prophetvs/editor/WaveBank.java src/com/prophetvs/editor/WaveBank.java
cp src-mac/com/prophetvs/editor/WaveCellRenderer.java src/com/prophetvs/editor/WaveCellRenderer.java
cp src-mac/com/prophetvs/editor/WaveFile.java src/com/prophetvs/editor/WaveFile.java
cp src-mac/com/prophetvs/editor/WaveView.java src/com/prophetvs/editor/WaveView.java
cp src-mac/com/prophetvs/editor/WaveWindow.java src/com/prophetvs/editor/WaveWindow.java
